### PR TITLE
Drop the clustering feature for Anbox Cloud Appliance

### PR DESCRIPTION
**Pull request by adglkh**

### CODE REVIEW

**Review by keirthana — APPROVED** [review]
LGTM! Just one additional change is required for the deleted pages:

They need to be deleted from the navigation table in `index.md`. I could do this as part of the publishing process if that's simpler.

**Review by keirthana — CHANGES_REQUESTED** [review]
The following entries must be removed from the Navigation table:

`| 3 | howto/cluster/appliance | [Join a machine to the appliance](https://discourse.ubuntu.com/t/how-to-join-a-machine-to-the-anbox-cloud-appliance/29054) |`

`|   | reference/appliance-command-reference/cluster | [Appliance command reference - cluster](https://discourse.ubuntu.com/t/39519)|`

**Comment by adglkh** [comment]
> howto/cluster/appliance

**Comment by adglkh** [comment]
> The following entries must be removed from the Navigation table:
> 
> `| 3 | howto/cluster/appliance | [Join a machine to the appliance](https://discourse.ubuntu.com/t/how-to-join-a-machine-to-the-anbox-cloud-appliance/29054) |`
> 
> `| | reference/appliance-command-reference/cluster | [Appliance command reference - cluster](https://discourse.ubuntu.com/t/39519)|`
A: Thanks for pointing that out.
    Please take another look

**Review by keirthana — APPROVED** [review]
LGTM!

**Review by morphis — APPROVED** [review]
LGTM

**Pull request merged**
