### PR TITLE
Upddate WebView version and bulletin link for 1.21.1 release notes

### PR DESCRIPTION
**Pull request by keirthana**

### CODE REVIEW

**Review by ajanon — APPROVED** [review]
LGTM

**Comment by jat-canonical** [comment]
I think we forgot to add [this](https://warthogs.atlassian.net/browse/AC-2298) one ? also david might have a couple to put in under a dashboard section i think since there were 2 fixes from their side in this release?

**Comment by keirthana** [comment]
> I think we forgot to add [this](https://warthogs.atlassian.net/browse/AC-2298) one ? also david might have a couple to put in under a dashboard section i think since there were 2 fixes from their side in this release?

AC-2298 was listed in 1.21.0 as fixed (backported), so I don't think we have to list that again and the dashboard team's bug fixes are listed in the common bug fixes section.

**Review by jat-canonical — APPROVED** [review]
Alright makes sense then. Thanks LGTM.

**Pull request merged**
