### PR TITLE
Feat: make the "older releases" section collapsible

### PR DESCRIPTION
**Pull request by ElAsJay**
Feat: make the "older releases" section collapsible

Make the "older releases" section collapsible

I used HTML tag <details>, and <summary> for making the "older releases" section collapsible. I moved the older releases tables inside the <details> tag.

Fix: fix the the broken tables for 2019 and 2018 headings

Fix the broken tables for 2019 and 2018 headings

I added the column headers in 2019 and 2018 releases tables

### CODE REVIEW

**Comment by keirthana** [comment]
@ElAsJay Thank you for your time on this.

The collapsible section does not seem to work, we can validate this locally by running `make run` from inside the repository and the documentation will be served on the local host. I did a little research and looks like the `<details>` tag does not work with multiple markdown headings inside it and the `<h2>` tag in the summary also hinders the collapisble element from being displayed properly.

I think we can collate all the older release notes into one big table and nest it inside the `<details>` tag.  We retain the older versions heading as before and provide a summary that guides users to click the expander to read earlier release notes. What do you think?

P.S: Also, could I ask you to sign the [CLA](https://ubuntu.com/legal/contributors) which is mandatory for contributors? If you have already, let me know. The CLA check sometimes takes a while to reflect the new members who have signed.

**Comment by ElAsJay** [comment]
@keirthana Thank you for the feedback.

I will change the markdown format to html codes, which occurred the problem inside the `<details>` tags.

Plus, I also signed the CLA with your name.

**Comment by keirthana** [comment]
> @keirthana Thank you for the feedback.
> 
> I will change the markdown format to html codes, which occurred the problem inside the `<details>` tags.

@ElAsJay Let me know if you need any help with this. 

> Plus, I also signed the CLA with your name.

Thank you

**Comment by keirthana** [comment]
@ElAsJay This will fixed as part of the upcoming patch release for Anbox Cloud (#142). So I am closing this PR without merging.

**Pull request closed without merging**
